# Generated by Django 3.1.5 on 2021-05-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_info_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
